### PR TITLE
Changes to avoid config deprecation warnings (from jasmine-core)

### PR DESCRIPTION
**Pull request by claudiosdc**
Change the way that certain configuration options are set to Jasmine's environment to be compliant with jasmine-core and avoid deprecation warnings.

### CODE REVIEW

**Comment by claudiosdc** [comment]
I realized that the solution was not complete, so I made these additional changes.

**Comment by charleshansen** [comment]
I can confirm there are deprecation warnings without this change and the warnings go away with the change. I tried it out with Jasmine 3.3 and the features seems to still work correctly. (Caveat, throwFailures and failFast never really do what I expect, so I can't say for 100% sure it is right). 

My main concern is that the new config options were introduced in Jasmine 3.3 (Oct 25). With this PR, the old features will break for people using Jasmine 3.2. We may need a grace period where we support both versions. This could also be fixed by setting an aggressive peer dependency for the new version requiring 3.3+.

**Comment by sweinstein22** [comment]
Hello from Apps Manager! We're also interested in these changes as we are using Jasmine 3.3.0, and were wondering whether it would be a viable option to branch on the version of Jasmine in use? It looks like the version is stored as a string on the jasmine object.

**Comment by rdy** [comment]
Sounds to me like we should lock down the new version to 3.3, I’d be happy to merge that change if we can adjust the PR for that.

**Comment by macinjosh32** [comment]
I’m interested in seeing these changes as well since we’re also using Jasmine v3.3.0. I’m ok with the addition of a peerDependency.

**Comment by jgonggrijp** [comment]
Ping @claudiosdc. Please see @rdy's invitation above to bump the jasmine-core version to 3.3.

**Comment by slackersoft** [comment]
Closing since gulp-jasmine-browser is discontinued

**Pull request closed without merging**
